version: '3.8'

services:
  bashupload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./bashupload.db:/app/bashupload.db
    environment:
      - PORT=3000
      - MAX_UPLOAD_SIZE=1GB  # Human readable: 100MB, 500MB, 1GB, 5GB, etc.
      - MAX_DOWNLOADS=1      # Number of times file can be downloaded (1=single download)
      - FILE_EXPIRE_AFTER=3D # File expiration: 1D, 1W, 1M, 1Y, etc.
      # - API_KEY=your_secret_api_key_here  # Uncomment and set for private instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - bashupload-network

networks:
  bashupload-network:
    driver: bridge

volumes:
  uploads:
  database: